name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-findings
        path: bandit-report.json

  image_scan:
    name: Build and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -f Dockerfile -t mytestapp:latest .

    - name: Docker Scout Scan
      uses: docker/scout-action@v1.15.1
      with:
        dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
        command: quickview,cves
        only-severities: critical,high
        sarif-file: scout-report.sarif
        exit-code: true

    - name: Upload Docker Scout Report
      uses: actions/upload-artifact@v4
      with:
        name: docker-scout-findings
        path: scout-report.sarif

  dast_scan:
    name: DAST Scan with Nikto
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy PyGoat
      run: |
        docker network create nikto-network
        docker run --rm --name pygoat --network nikto-network -d -p 8000:8000 pygoat/pygoat:latest

    - name: Install Nikto
      run: sudo apt-get update && sudo apt-get install -y nikto

    - name: Run Nikto Scan
      run: |
        nikto -h http://pygoat:8000 -o nikto-report.html -Format html
      env:
        DOCKER_HOST: "unix:///var/run/docker.sock"

    - name: Upload Nikto Report
      uses: actions/upload-artifact@v4
      with:
        name: nikto-findings
        path: nikto-report.html
