name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Check if Bandit Report Exists
      run: ls -l bandit-report.json

    - name: Upload Bandit Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bandit-findings
        path: bandit-report.json

  image_scan:
    name: Build and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -f Dockerfile -t mytestapp:latest .

    - name: Docker Scout Scan
      uses: docker/scout-action@v1.15.1
      with:
        dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
        command: quickview,cves
        only-severities: critical,high
        sarif-file: scout-report.sarif
        exit-code: true

    - name: Check if Docker Scout Report Exists
      run: ls -l scout-report.sarif

    - name: Upload Docker Scout Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-scout-findings
        path: scout-report.sarif

  dast_scan:
    name: DAST Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy PyGoat
      run: |
        docker pull pygoat/pygoat:latest
        docker run --rm -d -p 8000:8000 pygoat/pygoat:latest

    - name: Perform DAST Scan with OWASP ZAP
      uses: zaproxy/action-full-scan@v0.9.0
      with:
        target: "http://localhost:8000"
        fail_action: true
        artifact_name: zap-report

    - name: Check if ZAP Report Exists
      run: ls -l zap-report

    - name: Upload ZAP Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: zap-findings
        path: zap-report
